dist: xenial
sudo: required
language: sh
osx_image: xcode10.1

addons:
  apt:
    packages:
    - libxml2-utils

cache:
    directories:
     - .bazel_cache
     - ~/.bazel_binaries

os:
  - linux
  - osx
  - windows

###
#
# Want to update/change bazel versions?
#
# 1. Update the bazel_version case statement in
#    ./tools/bazel to include hashes for the bazel version
#    you're targeting.
#
# 2. either
#    - If you're updating the default bazel version, change
#      default_bazel_version in ./tools/bazel.
#    or
#    - If you want to add an additional bazel version to the build
#      matrix, set BAZEL_VERSION=<desired-version> along side
#      TEST_SCRIPT below.
#
# 3. If you need to update the Windows version, adjust
#    the windows specific install code below.
#
###

env:
  # Linting is broken. Disable until fixed.
  # See https://github.com/bazelbuild/rules_scala/pull/622
  # we want to test the last release
  - TEST_SCRIPT=test_lint
  - TEST_SCRIPT=test_rules_scala
  #- TEST_SCRIPT=test_intellij_aspect.sh
  - TEST_SCRIPT=test_reproducibility


before_install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "windows" ]]; then
      choco install jdk8 -params 'installdir=c:\\java8'
      choco install bazel --version 0.28.0
    fi
  - cat .bazelrc.travis >> .bazelrc

script:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "windows" ]]; then
      powershell -Command 'Set-ExecutionPolicy RemoteSigned -scope CurrentUser'
      export JAVA_HOME='c:\\\\java8'
      export BAZEL_VERSION=host
    fi
    bash ./${TEST_SCRIPT}.sh ci
